fn main() {
    println!("cargo::rerun-if-changed=LICENSE");
    let out_dir = std::env::var_os("OUT_DIR").unwrap();
    let path = std::path::Path::new(&out_dir).join("license.rs");
    let license_string = std::fs::read_to_string("LICENSE").expect("failed to read LICENSE file");
    let code_license_string = format!("
/*****************************************************************/
/*                                                               */
/* THIS FILE IS AUTOMATICALLY GENERATED DURING THE BUILD PROCESS */
/*                                                               */
/*****************************************************************/

pub static LICENSE: &str = \"{}\";",
        license_string.replace("\"", "\\\""));
    std::fs::write(&path, code_license_string).unwrap();
}
