use phf::phf_map;
use crate::cli::Language;

static LETTERS_GER: phf::Map<&'static str, &'static str> = phf_map! {
    "a" => "Aachen",
    "ä" => "Umlaut Aachen",
    "b" => "Berlin",
    "c" => "Chemnitz",
    "d" => "Düsseldorf",
    "e" => "Essen",
    "f" => "Frankfurt",
    "g" => "Goslar",
    "h" => "Hamburg",
    "i" => "Ingelheim",
    "j" => "Jena",
    "k" => "Köln",
    "l" => "Leipzig",
    "m" => "München",
    "n" => "Nürnberg",
    "o" => "Offenbach",
    "ö" => "Umlaut Offenbach",
    "p" => "Potsdam",
    "q" => "Quickborn",
    "r" => "Rostock",
    "s" => "Salzwedel",
    "ß" => "Eszett",
    "t" => "Tübingen",
    "u" => "Unna",
    "ü" => "Umlaut Unna",
    "v" => "Völklingen",
    "w" => "Wuppertal",
    "x" => "Xanten",
    "y" => "Ypsilon",
    "z" => "Zwickau",
};

static LETTERS_ENG: phf::Map<&'static str, &'static str> = phf_map! {
    "a" => "Alpha",
    "b" => "Bravo",
    "c" => "Charlie",
    "d" => "Delta",
    "e" => "Echo",
    "f" => "Foxtrot",
    "g" => "Golf",
    "h" => "Hotel",
    "i" => "India",
    "j" => "Juliett",
    "k" => "Kilo",
    "l" => "Lima",
    "m" => "Mike",
    "n" => "November",
    "o" => "Oscar",
    "p" => "Papa",
    "q" => "Quebec",
    "r" => "Romeo",
    "s" => "Sierra",
    "t" => "Tango",
    "u" => "Uniform",
    "v" => "Victor",
    "w" => "Whiskey",
    "x" => "X-ray",
    "y" => "Yankee",
    "z" => "Zulu",
};

pub fn lookup_letter(letter: &str, language: Language) -> Option<&str> {
    match language {
        Language::German => &LETTERS_GER,
        Language::English => &LETTERS_ENG,
    }.get(letter).map(|v| &**v)
}
